name: sergio
favicon: null
layout_spectrum: 0.8458648633677512
typography_spectrum: 0.5180371645838022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.305642977822572
  lightness: 0.9862073149997741
  saturation: 0.02845510537736118
  rhythmicContrast: 0.002644067630171776
purpose: []
